version: '3'
services:
  # Gunicorn service
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.gunicorn
    # remove the port mapping - not needed for direct access
    networks:
      - app-network
  
  # Nginx service
  webserver:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80  # Expose NGINX on port 80 of the host machine
    depends_on:
      - api
    networks:
      - app-network
  
  #  SSL service
  ssl:
    build:
      context: .
      dockerfile: ./Dockerfile.ssl
    depends_on:
      - webserver
    networks:
      - app-network

networks:
  app-network: