version: '3'

services:
  botpress:
    build:
      context: ./botpress
      dockerfile: Dockerfile
    image: botpress/server
    container_name: botpress-server
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:DB101101@postgres:5435/botpress_db
      - BP_MODULE_NLU_DUCKLINGURL=http://botpress_lang:8000
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://botpress_lang:3100"}]
      - EXTERNAL_URL=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - ./botpress/data:/botpress/data

  botpress_lang:
    build:
      context: ./botpress
      dockerfile: Dockerfile
    image: botpress/server
    container_name: botpress-lang
    command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
    expose:
      - 3100
      - 8000
    volumes:
      - ./botpress/language:/botpress/lang

  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5435:5435
    container_name: postgres
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: DB101101
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root2222
      ports:
        - "8080:80"
        
  football_api:
      container_name: football-server
      restart: always
      build:
          context: ./football_api
          dockerfile: Dockerfile
      environment:
          model_path: "nlu-20221225-083208-molto-pentatonic.tar.gz"
          football_api_key: "d20816f6bfmsh4bd8471a7d15f8bp109432jsn5459274f3f36"
      ports:
          - "8000:8000"

volumes:
  pgdata:
