version: '3'
services:
  # Gunicorn service
  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile.gunicorn
    env_file:
      - .env
    # remove the port mapping - not needed for direct access
    networks:
      - app-network
  
  # Nginx service
  webserver:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80  # Expose NGINX on port 80 of the host machine
    depends_on:
      - webapi
    networks:
      - app-network
    
  # Certbot service
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


    