# Use the Nginx image from Docker Hub

# Not nginx:latest, use nginx:alpine because of its SSL support
FROM nginx:alpine 

# update and install gettext for envsubst (env vars in nginx.conf)
RUN apt-get update && apt-get install -y gettext

# Copy config file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy env_vars file
COPY env_vars /

# Replace env vars in nginx.conf
RUN envsubst < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf

# include certbot installation
RUN apk add --no-cache certbot

# Expose port 80
EXPOSE 80

# No need since nginx image already has this command
# CMD ["nginx", "-g", "daemon off;"]
